---
dependencies:
- name: "jenkins"
  repository: "http://chartmuseum.thunder.35.189.66.194.nip.io"
  version: "0.9.2"
- name: "sonatype-nexus"
  repository: "http://chartmuseum.thunder.35.189.66.194.nip.io"
  version: "0.1.1"
- name: "pipelines"
  repository: "file://pipelines"
  version: "0.0.2"
- name: "exposecontroller"
  repository: "file://exposecontroller"
  version: "0.0.1"
- name: "pipelinecontroller"
  repository: "file://pipelinecontroller"
  version: "0.0.1"
