---
dependencies:
- name: jenkins
  version: 0.9.2
  repository: http://chartmuseum.thunder.35.189.66.194.nip.io
- name: sonatype-nexus
  version: 0.1.1
  repository: http://chartmuseum.thunder.35.189.66.194.nip.io
- name: pipelines
  version: 0.0.1
  repository: file://pipelines
- name: exposecontroller
  version: 0.0.1
  repository: file://exposecontroller
- name: pipelinecontroller
  version: 0.0.1
  repository: file://pipelinecontroller
